### ISSUE TITLE
issue in use from pracmln in python 

### ISSUE THREAD

**Issue by abbasi72** [danielnyga/pracmln#13]
hello ....
I install pracmln with " pip install pracmln" but i could not use from it and see this error....please guide me .....
runfile('C:/Users/abbasi/.spyder/temp.py', wdir='C:/Users/abbasi/.spyder')
Traceback (most recent call last):

  File "<ipython-input-1-7c27da7b97a6>", line 1, in <module>
    runfile('C:/Users/abbasi/.spyder/temp.py', wdir='C:/Users/abbasi/.spyder')

  File "C:\Users\abbasi\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\abbasi\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/abbasi/.spyder/temp.py", line 7, in <module>
    from pracmln import MLN

  File "C:\Users\abbasi\Anaconda2\lib\site-packages\pracmln\__init__.py", line 21, in <module>
    from mln.base import MLN

  File "C:\Users\abbasi\Anaconda2\lib\site-packages\pracmln\mln\__init__.py", line 27, in <module>
    from base import MLN

  File "C:\Users\abbasi\Anaconda2\lib\site-packages\pracmln\mln\base.py", line 27, in <module>
    from dnutils import logs, ifnone, out

  File "C:\Users\abbasi\Anaconda2\lib\site-packages\dnutils\__init__.py", line 10, in <module>
    from .signals import add_handler, rm_handler, enable_ctrlc

  File "C:\Users\abbasi\Anaconda2\lib\site-packages\dnutils\signals.py", line 11, in <module>
    SIGKILL = signal_.SIGKILL

AttributeError: 'module' object has no attribute 'SIGKILL'

**Comment by mac389** [comment]
I get a related error after `pip install pracmln
`
`AttributeError: 'module' object has no attribute 'SIGCLD'`

**Comment by nodyyu89** [comment]
I solved this issue by replacing signals.py located in dnutils library with the following:

I am using windows 10 and python 3.5.4

`import signal as signal_
import threading
from collections import defaultdict

__usrreg = defaultdict(list)
__sysinit = defaultdict(list)
__systerm = defaultdict(list)

SIGINT = signal_.SIGINT
SIGTERM = signal_.SIGTERM
#SIGKILL = signal_.SIGKILL
SIGABRT = signal_.SIGABRT
#SIGALRM = signal_.SIGALRM
#SIGBUS = signal_.SIGBUS
#SIGCHLD = signal_.SIGCHLD
#SIGCLD = signal_.SIGCLD
#SIGCONT = signal_.SIGCONT
SIGFPE = signal_.SIGFPE
#SIGHUP = signal_.SIGHUP
SIGILL = signal_.SIGILL
SIGINT = signal_.SIGINT
#SIGIO = signal_.SIGIO
#SIGIOT = signal_.SIGIO
#SIGKILL = signal_.SIGKILL
#SIGPIPE = signal_.SIGPIPE
#SIGPOLL = signal_.SIGPOLL
#SIGPROF = signal_.SIGPROF
# =============================================================================
# SIGPWR = signal_.SIGPWR
# SIGQUIT = signal_.SIGQUIT
# SIGRTMAX = signal_.SIGRTMAX
# SIGRTMIN = signal_.SIGRTMIN
SIGSEGV = signal_.SIGSEGV
# SIGSTOP = signal_.SIGSTOP
# SIGSYS = signal_.SIGSYS
SIGTERM = signal_.SIGTERM
# SIGTRAP = signal_.SIGTRAP
# SIGTSTP = signal_.SIGTSTP
# SIGTTIN = signal_.SIGTTIN
# SIGTTOU = signal_.SIGTTOU
# SIGURG = signal_.SIGURG
# SIGUSR1 = signal_.SIGUSR1
# SIGUSR2 = signal_.SIGUSR2
# SIGVTALRM = signal_.SIGVTALRM
# SIGWINCH = signal_.SIGWINCH
# SIGXCPU = signal_.SIGXCPU
# SIGXFSZ = signal_.SIGXFSZ
# =============================================================================

_lock = threading.Lock()


def _run_handlers(signal, args):
    '''Executes all handlers that are registered for the given
    siganl in the order of registration.'''
    # run system handlers for preparing the signal handling
    for handler in __sysinit[signal]:
        handler(*args)
    # run user defined signal handlers
    for handler in __usrreg[signal]:
        handler(*args)
    # run system handlers for cleaning up the signal handling
    for handler in __systerm[signal]:
        handler(*args)


def add_handler(signal, handler):
    '''
    Add a handler to be executed on the signal ``signal``

    :param signal:  the signal to react to.
    :param handler: a callable that will be called on the signal.
    :return:
    '''
    _add_handler(signal, handler, __usrreg)


def _add_handler(signal, handler, registry):
    '''
    Add a handler to be executed on the signal ``signal``

    :param signal:  the signal to react to.
    :param handler: a callable that will be called on the signal.
    :return:
    '''
    with _lock:
        handlers_ = registry[signal]
        if not handlers_:
            signal_.signal(signal, lambda *args: _run_handlers(signal, args))
        if handler not in handlers_:
            handlers_.insert(0, handler)


def rm_handler(signal, handler):
    '''
    Remove a handler if it is registered to the given signal.
    :param signal:  the signal that the handler is registered for
    :param handler: the handler function.
    :return:
    '''
    _rm_handler(signal, handler, __usrreg)


def _rm_handler(signal, handler, registry):
    '''
    Remove a handler if it is registered to the given signal.
    :param signal:  the signal that the handler is registered for
    :param handler: the handler function.
    :return:
    '''
    with _lock:
        try:
            registry[signal].remove(handler)
        except ValueError:
            pass


def keyint(*_):
    raise KeyboardInterrupt()


def enable_ctrlc():
    '''
    Allows to interrupt the main thread by pressing Ctrl-C.
    :return:
    '''
    _add_handler(SIGINT, keyint, __systerm)


def disable_ctrlc():
    '''
    Disables interruption of the main thread by the Ctrl-C key combination.
    :return:
    '''
    _rm_handler(SIGINT, keyint, __systerm)`

**Comment by danielnyga** [comment]
Fixed in dnutils release 0.2.12.

**Comment by algoessmann** [comment]
Hello! It seems that the error is still there. I am using macOS, python3.8.5. and dnutils 0.2.12.
